exports.Map = require('./components/Map.vue')
exports.TileLayer = require('./components/TileLayer.vue')
exports.Marker = require('./components/Marker.vue')
exports.Tooltip = require('./components/Tooltip.vue')
exports.Popup = require('./components/Popup.vue')
exports.LayerGroup = require('./components/LayerGroup.vue')
exports.GeoJson = require('./components/GeoJson.vue')
